services:
  app_my_go:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_MY_GO_HASURA_SERVICE_TOKEN_SECRET
      MUTATION_CONCURRENCY_LIMIT: $APP_MY_GO_MUTATION_CONCURRENCY_LIMIT
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_MY_GO_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MY_GO_OTEL_SERVICE_NAME
      QUERY_CONCURRENCY_LIMIT: $APP_MY_GO_QUERY_CONCURRENCY_LIMIT
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - mode: ingress
        protocol: tcp
        published: "8359"
        target: 8080
